project:
  type: website
  output-dir: docs

website:
  title: "Walker Bicentennial Farm"
  navbar:
    right:
      - href: index.qmd
        text: " "
        icon: house
      - href: history.qmd
        text: The Farm
      - href: about.qmd
        text: About
      - href: contact.qmd
        text: Contact
      - href: beef.qmd
        text: Beef
      - href: "https://www.facebook.com/walkerbicentennial"
        icon: facebook
    background: black
    foreground: red
    pinned: true

   ## font-family: Adobe Devanagari !important
   ## font-size: 5.0em !important
  ##  logo: 
  search: false
  repo-url: https://github.come/walkerbicentennial/walkerbicentennial.github.io
  repo-actions: [edit, issue]
  
  
format:
  html:
    theme: journal
    css: styles.css
    toc: true
    fontsize: 1.5em
    fontcolor: white
    Linestretch: 0.5
    backgroundcolor: gray
   



