project:
  type: website
  output-dir: docs

website:
  title: "Walker Bicentennial Farm"
  site-url: https://walkerbicentennial.github.io/
  favicon: "images/logo.jpg"
  navbar:
    logo: images/logo.jpg
    right:
      - href: history.qmd
        text: About
      - href: contact.qmd
        text: Contact
      - text: Beef 
        menu: 
          - text: 2024 Custom Butchered Beef
            href: pricing.qmd
          - text: The Butcher
            href: butcher.qmd
          - text: Cuts of Meat
            href: meat.qmd
          - text: Order policy
            href: policy.qmd
      - href: "tel:13305753957"
      - href: "mailto:walkerbicentennial@gmail.com"
        icon: envelope
      - href: "https://www.facebook.com/walkerbicentennial"
        icon: facebook
      - href: "https://www.instagram.com/walkerbicentennial"
        icon: instagram

    background: "#ffffff" #white
    mainfont: Adobe Devanagari
    foreground: "#cc0000" # red
    pinned: true
  search: false
  page-footer: 
    right: 
      - text: "13942 Warren Road NE 
               Paris, Ohio 44669"
    center: 
      - href: "tel:13305753957"
        icon: telephone
      - href: "mailto:walkerbicentennial@gmail.com"
        icon: envelope
      - href: "https://www.facebook.com/walkerbicentennial"
        icon: facebook
      - href: "https://www.instagram.com/walkerbicentennial"
        icon: instagram
    left: 
      - text: "2023 Walker Bicentennial Farm"       
        icon: c-circle
    foreground: "#cc0000" # red
  
format:
  html:
    theme: journal
    css: journal.scss
    toc: true
    fontsize: 1.5em
    fontcolor: "#ffffff" # white
    Linestretch: 0.5
    backgroundcolor: black
    linkcolor: white
    foreground: "#cc0000" # red
    mainfont: Adobe Devanagari
   



